### ISSUE TITLE
[Question] About running hydrojudge on Windows

### ISSUE THREAD

**Issue by riverstore** [hydro-dev/Hydro#275]
Hi, from [部署 Hydro](https://hydro.js.org/docs/install/#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%80%89%E6%8B%A9) , it's said that **Hydrojudge** can't work on non-Linux systems.

But I found that Hydrojudge use go-judge for judging and go-judge support Windows.

Do it's hard to make Hydrojudge to support Windows? And will Hypro support Windows in the future?

Thanks and best regrad.

**Comment by undefined-moe** [comment]
In Windows, sandboxing is implemented by downgrading user permissions, and the file system control is not implemented.

You may experience problems below:

- Unstable running time
- Downgraded performance (no tmpfs support, which causes lots of disk I/O)
- Maybe permission issue (untested)
- Unusual line endings ( `\r\n` )
- Different path sep ( `\` instead of `/` )

Hydro-Web service should support Windows, but Windows support for judge won't be in our plan. (and its cheaper and easier to use a Linux system on cloud platforms)

So its suggested to run in Linux.
For linux users, compilers were commonly installed using `apt-get`, which installs at the same path on diffferent machine.
But in Windows they are different, so we cannot provide a builtin configuration.
If you really want to use Windows to run judge, you have to build the sandbox rootfs and configure compiler commands by yourself.
This might work, but with no warranty.

**Comment by riverstore** [comment]
Thank a lot for the detail and very fast answer. I'm glad to hear that Hydrojudge can work on Windows. In my country, most of highschool use Windows, with team about 1-6 members, and teachers may use Judge systems on LAN only, and above problems may "aceptable". I'll try to understand Hydrojudge and make it work on Windows (hope I can :) )

Thanks a lot for your great work.

Regard.

**Comment by undefined-moe** [comment]
Suggested to use wsl2 or virtualbox vm :D

**Comment by riverstore** [comment]
Thanks a lot for your suggestion. I forget that we have wsl2 on Windows. ^^

**Comment by riverstore** [comment]
@undefined-moe I write this comment just to notice that I can judge `C`, `C++`, `Free Pascal`, `Python` on Windows 10 **without change a line of `Hydro` code**, I just change settings in `Code language settings` from `System setting` and it's working fine now.

Again, thanks a lot for your hard work.

Best regard.

PS: Hope you see this comment. I'm really happy ^^

**Comment by undefined-moe** [comment]
Glad to hear this :D
